steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/basketball-academy', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/basketball-academy']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'basketball-academy', '--image', 'gcr.io/$PROJECT_ID/basketball-academy', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY