steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/basketball-academy/app:$SHORT_SHA', '.']
    id: 'build-image'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/basketball-academy/app:$SHORT_SHA']
    id: 'push-image'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'basketball-academy'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/basketball-academy/app:$SHORT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--max-instances'
      - '10'
      - '--service-account'
      - 'basketball-academy-sa@basketball-academy-baf77.iam.gserviceaccount.com'
    id: 'deploy'

# Store images in Artifact Registry
images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/basketball-academy/app:$SHORT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  substitutions:
    _SERVICE_NAME: basketball-academy
    _REGION: asia-southeast1

# Build timeout
timeout: '1200s'